### ISSUE TITLE
NET 6.0 Support missing

### ISSUE THREAD

**Issue by Eesof** [FrendsPlatform/Frends.Xml#18]
Will this be ported to support NET 6.0? Cross platforms agents are now days using it.

**Comment by jefim** [comment]
Hello, the .NET 6 support is implemented in https://github.com/FrendsPlatform/Frends.CrossplatformXML. We currently have Transform and XPathQuery ready there.

**Comment by Eesof** [comment]
> 

Happy to hear it! Permissions won't let see anything in that link yet(might be on purpose).
